### ISSUE TITLE
Retroalimentación

### ISSUE THREAD

**Issue by Ryuuba** [NataliaVictoria/I7#1]
El contenido del archivo README.md es difícil de leer. Agreguen saltos de línea para separar los párrafos. Igualmente, valdría la pena que 

Falta que en este mismo archivo agreguen los dos siguientes contenidos:

- la estructura de directorios que utilizaron en su proyecto y
- una sección de ejemplos donde se ilustre como utilizar cada función que integra su biblioteca.

La documentación de la cabecera es correcta, pero podría completarse con la anotación `@author`.

Debido a la carencia de la estructura de directorios, deberán compilar un proyecto diseñado por mí para demostrar que saben manejar rutas relativas. Después de esta actividad, asentaré su calificación en Ubicua.

Las bibliotecas se enlazan correctamente al código de mi función `main`.

Atiendan los comentarios que les indico antes de la medianoche del domingo 21 de agosto de 2022. Al atender estos comentarios, estarán asegurando que cumplen con los requisitos especificados en I7.

Si tienen alguna duda, envien un mensaje directo a mi cuenta de Telegram.

**Comment by NataliaVictoria** [comment]
Se han hecho las modificaciones pertinentes.
Ahora la documentación de las cabeceras ya tiene `@author.`
El archivo README  tiene estructura de directorios y ejemplos. Además, el archivo tiene un formato más legible. :)
